version: '2'

services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    ports:
    - 8090:8090
    depends_on:
     - db
     
  db:
     image: 'postgres:13.1-alpine'
     container_name: db
     environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: capg1234
      POSTGRES_DB: employee
     
   
  